### ISSUE TITLE
Shapely 1.8.0 error - no output

### ISSUE THREAD

**Issue by mariana-s-fernandes** [abey79/hatched#5]
I had to fix Shapely version on 1.7.1 since I was getting an exception/error.
My OS is Windows 10, Python 3.9.10 and Shapely 1.8.0. 

The code ran but didn't write any output. Here is the error trace:

```>vpype hatched --levels 20 100 180 -p 5 -b 1 skull.png write put.svg
C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\hatched\hatched.py:246: ShapelyDeprecationWarning: The proxy geometries (through the 'asShape()', 'asMultiLineString()' or 'MultiLineStringAdapter()' constructors) are deprecated and will be removed in Shapely 2.0. Use the 'shape()' function or the standard 'MultiLineString()' constructor instead.
  mls, black_cnt, dark_cnt, light_cnt = _build_hatch(
Exception ignored in: <function BaseGeometry.__del__ at 0x000002596302D3A0>
Traceback (most recent call last):
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 209, in __del__
    self._empty(val=None)
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 199, in _empty
    self._is_empty = True
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\proxy.py", line 44, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
Exception ignored in: <function BaseGeometry.__del__ at 0x000002596302D3A0>
Traceback (most recent call last):
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 209, in __del__
    self._empty(val=None)
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 199, in _empty
    self._is_empty = True
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\proxy.py", line 44, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
Exception ignored in: <function BaseGeometry.__del__ at 0x000002596302D3A0>
Traceback (most recent call last):
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 209, in __del__
    self._empty(val=None)
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 199, in _empty
    self._is_empty = True
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\proxy.py", line 44, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
Exception ignored in: <function BaseGeometry.__del__ at 0x000002596302D3A0>
Traceback (most recent call last):
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 209, in __del__
    self._empty(val=None)
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 199, in _empty
    self._is_empty = True
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\proxy.py", line 44, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
Exception ignored in: <function BaseGeometry.__del__ at 0x000002596302D3A0>
Traceback (most recent call last):
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 209, in __del__
    self._empty(val=None)
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 199, in _empty
    self._is_empty = True
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\proxy.py", line 44, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
Exception ignored in: <function BaseGeometry.__del__ at 0x000002596302D3A0>
Traceback (most recent call last):
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 209, in __del__
    self._empty(val=None)
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 199, in _empty
    self._is_empty = True
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\proxy.py", line 44, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\hatched\hatched.py:197: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  [ls for ls in light_mls] + [ls for ls in dark_mls] + [ls for ls in black_mls]

(art) C:\Users\maria\Desktop\Plotter\Cutes>vpype hatched --levels 20 100 180 -p 5 -b 1 skull.png show
C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\hatched\hatched.py:246: ShapelyDeprecationWarning: The proxy geometries (through the 'asShape()', 'asMultiLineString()' or 'MultiLineStringAdapter()' constructors) are deprecated and will be removed in Shapely 2.0. Use the 'shape()' function or the standard 'MultiLineString()' constructor instead.
  mls, black_cnt, dark_cnt, light_cnt = _build_hatch(
Exception ignored in: <function BaseGeometry.__del__ at 0x0000025A3837E3A0>
Traceback (most recent call last):
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 209, in __del__
    self._empty(val=None)
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 199, in _empty
    self._is_empty = True
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\proxy.py", line 44, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
Exception ignored in: <function BaseGeometry.__del__ at 0x0000025A3837E3A0>
Traceback (most recent call last):
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 209, in __del__
    self._empty(val=None)
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 199, in _empty
    self._is_empty = True
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\proxy.py", line 44, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
Exception ignored in: <function BaseGeometry.__del__ at 0x0000025A3837E3A0>
Traceback (most recent call last):
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 209, in __del__
    self._empty(val=None)
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 199, in _empty
    self._is_empty = True
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\proxy.py", line 44, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
Exception ignored in: <function BaseGeometry.__del__ at 0x0000025A3837E3A0>
Traceback (most recent call last):
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 209, in __del__
    self._empty(val=None)
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 199, in _empty
    self._is_empty = True
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\proxy.py", line 44, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
Exception ignored in: <function BaseGeometry.__del__ at 0x0000025A3837E3A0>
Traceback (most recent call last):
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 209, in __del__
    self._empty(val=None)
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 199, in _empty
    self._is_empty = True
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\proxy.py", line 44, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
Exception ignored in: <function BaseGeometry.__del__ at 0x0000025A3837E3A0>
Traceback (most recent call last):
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 209, in __del__
    self._empty(val=None)
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\base.py", line 199, in _empty
    self._is_empty = True
  File "C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\shapely\geometry\proxy.py", line 44, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
C:\Users\maria\Documents\genart\vsketch\art\lib\site-packages\hatched\hatched.py:197: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  [ls for ls in light_mls] + [ls for ls in dark_mls] + [ls for ls in black_mls] ```

**Comment by abey79** [comment]
Good point. I need to update this plug-in for Shapely 1.8.

If you want to take a shot at it, you may check the [Shapely 1.8 migration guide](https://shapely.readthedocs.io/en/stable/migration.html).

**Comment by mariana-s-fernandes** [comment]
I don't think I have the skills for that yet :)

**Comment by mariana-s-fernandes** [comment]
Shapely upgraded in https://github.com/plottertools/hatched/pull/9
